<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'code' => 'FIC001',
                'title' => 'Adventures in Fiction',
                'description' => 'A captivating tale of adventure and fantasy. Adventures in Fiction is a thrilling story that takes readers on a journey to far-off lands and magical realms. From dragons to wizards, the book is filled with enchanting characters and exciting adventures. Each chapter is filled with vivid descriptions and engaging dialogue, making it easy to lose yourself in the story. Whether you are a fan of fantasy fiction or just looking for an escape from reality, Adventures in Fiction has something for everyone.',
                'author_id' => 11,
                'isbn' => '9781234567890',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-01-15'),
                'publisher' => 'Fiction House',
                'pages' => 350,
                'lessons' => null,
                'rating' => 4.5,
                'min_age' => 10,
                'quantity' => 20,
                'purchase_price' => 12.50,
                'sale_price' => 15.00,
                'discounted_price' => 13.50,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'NF001',
                'title' => 'The World of Facts',
                'description' => 'An exploration of fascinating facts from around the globe. The World of Facts is a collection of interesting and informative tidbits about the world we live in. From geography to history, the book covers a wide range of topics in an engaging and accessible style. Each fact is accompanied by colorful illustrations and fun anecdotes, making it easy to learn something new every day. Whether you are a trivia buff or just curious about the world, The World of Facts has something for everyone.',
                'author_id' => 12,
                'isbn' => '9782345678901',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-03-10'),
                'publisher' => 'Knowledge Press',
                'pages' => 220,
                'lessons' => null,
                'rating' => 4.0,
                'min_age' => 12,
                'quantity' => 50,
                'purchase_price' => 8.00,
                'sale_price' => 10.00,
                'discounted_price' => 9.00,
                'discount_type' => 'percentage',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 0,
                'on_sale' => 1,
                'free_delivery' => 0,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'SCI001',
                'title' => 'Discovering the Universe',
                'description' => 'An in-depth look into the wonders of the cosmos. Discovering the Universe is a comprehensive guide to the mysteries of space and time. From the Big Bang to black holes, the book covers a wide range of topics in astronomy and astrophysics. Each chapter is filled with stunning photographs and detailed explanations, making it easy to understand the complex concepts of the universe. Whether you are a science enthusiast or just curious about the cosmos, Discovering the Universe has something for everyone.',
                'author_id' => 3,
                'isbn' => '9783456789012',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-05-21'),
                'publisher' => 'Science Today',
                'pages' => 300,
                'lessons' => null,
                'rating' => 4.8,
                'min_age' => 14,
                'quantity' => 30,
                'purchase_price' => 15.00,
                'sale_price' => 18.00,
                'discounted_price' => 16.50,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'HIS001',
                'title' => 'History of Civilizations',
                'description' => 'A comprehensive guide to the rise and fall of civilizations. History of Civilizations is a detailed account of the major civilizations that have shaped human history. From ancient Mesopotamia to modern-day America, the book covers a wide range of cultures and societies. Each chapter is filled with fascinating facts and insights, making it easy to learn about the key events and figures of each era. Whether you are a history buff or just curious about the world, History of Civilizations has something for everyone.',
                'author_id' => 4,
                'isbn' => '9784567890123',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-08-10'),
                'publisher' => 'History Press',
                'pages' => 500,
                'lessons' => null,
                'rating' => 4.7,
                'min_age' => 16,
                'quantity' => 40,
                'purchase_price' => 20.00,
                'sale_price' => 25.00,
                'discounted_price' => 22.00,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'FAN001',
                'title' => 'Magical Realms',
                'description' => 'A journey into worlds of magic and wonder. Magical Realms is a collection of fantasy stories that transport readers to far-off lands and mystical realms. From dragons to wizards, the book is filled with enchanting characters and captivating adventures. Each story is written in a vivid and imaginative style, making it easy to lose yourself in the magic. Whether you are a fan of fantasy fiction or just looking for an escape from reality, Magical Realms has something for everyone.',
                'author_id' => 5,
                'isbn' => '9785678901234',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-10-15'),
                'publisher' => 'Fantasy Worlds',
                'pages' => 450,
                'lessons' => null,
                'rating' => 4.9,
                'min_age' => 10,
                'quantity' => 60,
                'purchase_price' => 18.00,
                'sale_price' => 22.00,
                'discounted_price' => 20.00,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'BIO001',
                'title' => 'Life of Legends',
                'description' => 'Biographies of people who shaped history. Life of Legends is a collection of biographies that tells the stories of some of the most influential figures in history. From political leaders to cultural icons, the book covers a wide range of personalities and achievements. Each biography is written in an engaging and informative style, making it easy to learn about the lives and legacies of these remarkable individuals. Whether you are a history buff or just curious about the world, Life of Legends has something for everyone.',
                'author_id' => 6,
                'isbn' => '9786789012345',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2022-12-20'),
                'publisher' => 'Biography Today',
                'pages' => 400,
                'lessons' => null,
                'rating' => 4.3,
                'min_age' => 14,
                'quantity' => 70,
                'purchase_price' => 16.00,
                'sale_price' => 20.00,
                'discounted_price' => 18.00,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'SPO001',
                'title' => 'Winning Spirit',
                'description' => 'Strategies for success in sports and life. Winning Spirit is a motivational book that offers practical advice on how to achieve success in sports and life. It covers a wide range of topics, including goal setting, mental toughness, and teamwork. The book is written by a former professional athlete who shares his personal experiences and insights. Whether you are an athlete, coach, or sports enthusiast, Winning Spirit can help you reach your full potential and achieve your goals.',
                'author_id' => 7,
                'isbn' => '9787890123456',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2023-02-15'),
                'publisher' => 'Sports Enthusiast',
                'pages' => 320,
                'lessons' => null,
                'rating' => 4.2,
                'min_age' => 12,
                'quantity' => 80,
                'purchase_price' => 14.00,
                'sale_price' => 17.00,
                'discounted_price' => 15.00,
                'discount_type' => 'fixed',
                'image' => 'assets/img/default-150x150.png',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'SELF001',
                'title' => 'The Path to Success',
                'description' => 'Guidance and tips on personal growth and development. The Path to Success is a self-help book that offers practical advice on how to achieve success in life. It covers a wide range of topics, including goal setting, time management, and overcoming obstacles. The book is written in a clear and engaging style, making it easy to read and understand. Whether you are looking to improve your career, relationships, or personal well-being, The Path to Success can help you reach your goals.',
                'author_id' => 8,
                'isbn' => '9788901234567',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2023-04-10'),
                'publisher' => 'Self-Help Publishing',
                'pages' => 270,
                'lessons' => null,
                'rating' => 4.6,
                'min_age' => 16,
                'quantity' => 90,
                'purchase_price' => 12.00,
                'sale_price' => 14.00,
                'discounted_price' => 13.00,
                'discount_type' => 'fixed',
                'image' => 'images/books/12/202406261813275004.jpg',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'COOK001',
                'title' => 'Culinary Delights',
                'description' => 'A collection of recipes from around the world. Culinary Delights is a cookbook that features a wide variety of recipes from different cuisines. From appetizers to desserts, the book covers all the essentials of cooking. Each recipe is accompanied by detailed instructions and full-color photographs, making it easy to follow along. Whether you are a seasoned chef or a novice cook, Culinary Delights has something for everyone. With its diverse selection of dishes, the book is sure to inspire you to get creative in the kitchen.',
                'author_id' => 9,
                'isbn' => '9789012345678',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2023-06-05'),
                'publisher' => 'Culinary Books',
                'pages' => 150,
                'lessons' => null,
                'rating' => 4.1,
                'min_age' => 12,
                'quantity' => 100,
                'purchase_price' => 10.00,
                'sale_price' => 12.00,
                'discounted_price' => 11.00,
                'discount_type' => 'fixed',
                'image' => 'images/books/13/202406262212305035.jpg',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'code' => 'TRAV001',
                'title' => 'Wanderlust Adventures',
                'description' => 'Exploring exotic travel destinations and experiences. Wanderlust Adventures is a travel guide that takes you on a journey to some of the most beautiful and exciting places in the world. From tropical beaches to ancient ruins, the book covers a wide range of destinations and experiences. Each chapter is filled with stunning photographs and detailed descriptions, making it easy to imagine yourself in these far-off locales. Whether you are a seasoned traveler or a novice explorer, Wanderlust Adventures has something for everyone. With its inspiring stories and practical tips, the book is sure to ignite your wanderlust and inspire you to plan your next adventure.',
                'author_id' => 10,
                'isbn' => '9780123456789',
                'edition_language' => 'English',
                'publication_date' => Carbon::parse('2023-08-01'),
                'publisher' => 'Travel Globe',
                'pages' => 240,
                'lessons' => null,
                'rating' => 4.4,
                'min_age' => 18,
                'quantity' => 110,
                'purchase_price' => 11.00,
                'sale_price' => 13.00,
                'discounted_price' => 12.00,
                'discount_type' => 'fixed',
                'image' => 'images/books/14/202406262218147897.jpeg',
                'availability' => 1,
                'featured' => 1,
                'on_sale' => 1,
                'free_delivery' => 1,
                'status' => 'published',
                'isDeleted' => 'no',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
